services:
  - type: web
    name: kawsar-codex-like-web
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --config gunicorn.conf.py --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
    healthCheckPath: /login
    autoDeploy: true
